baseURL = "https://mrunalnshah.github.io/"
languageCode = "en-us"
title = "mrunalnshah's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Mrunal Nirajkumar Shah"
  description = "Patience and Gratitude"
  github = "mrunalnshah"
  linkedin = "mrunalnshah"
  instagram = "mrunalnshah"
  email = "mrunalnshah2883@gmail.com"
  url = "https://mrunalnshah.github.io"
  keywords = "ai, ml, system, programming, project, coding, blog, google analytics"
  rss = false
  lastmod = true
  userStatusEmoji = "🐼"
  favicon = "/images/WildeWulf.png"
  avatar = "/images/prof_pic.png"
  headerIcon = "/images/WildeWulf.png"
  location = "Unknown Wilderness"
  enableGitalk = false
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

  [[params.links]]
    title = "Link"
    href = "https://github.com/mrunalnshah"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
